insert into user_status values (1,'default');
insert into user_roles values (1,'admin',1);
insert into long_quotas (long_quotaid, label) values (1,'default long quota');
insert into day_quotas (day_quotaid, label) values (1,'default day quota');
insert into constraint_functions values (1,'');
insert into time_block_groups values (1, 'default day layout');
insert into time_blocks values (1, 'default time block');
insert into organizations values (1, 'default organization');
insert into groups values (1, 'default group');
insert into reservation_type values (1, 'default');
insert into reservation_status values (1, 'default');