<?php
require_once('IValidator.php');
require_once('PageValidators.php');
require_once('EmailValidator.php');
require_once('RequiredValidator.php');
require_once('EqualValidator.php');
require_once('RegexValidator.php');
require_once('UniqueEmailValidator.php');
require_once('UniqueUserNameValidator.php');
?>